### ISSUE TITLE
Percentagepricesetfield error using Stripe and small amounts

### ISSUE THREAD

**Issue by mcollopy** [twomice/com.joineryhq.percentagepricesetfield#36] opened 2020-06-11 00:16 UTC
Stripe Payment processor throws an error message when contribution price set amounts are below $50: e.g. small amount like $10, $20 etc

`Credit Card This PaymentIntent's amount could not be updated because it has a status of requires_capture.`

- I could replicate the 'requires_capture' issue using these amounts
- $50 was successful test and live
- note I was testing on small amounts earlier, and it may explain why I was still getting issues with v1.5.0

Related issue https://github.com/twomice/com.joineryhq.percentagepricesetfield/issues/27

**Comment by twomice** [comment] 2020-06-11 00:46
Thanks for creating this ticket Mick. Tell me, do we need to use taxation 
and taxable financial types to reproduce this, or is it just the specifics 
you've mentioned so far?


On June 10, 2020 7:16:46 PM Mick Collopy <notifications@github.com> wrote:
> Stripe Payment processor throws an error message when contribution price 
> set amounts are below $50: e.g. small amount like $10, $20 etc
>
> Credit Card This PaymentIntent's amount could not be updated because it has 
> a status of requires_capture.
>
> I could replicate the 'requires_capture' issue using these amounts
> $50 was successful test and live
> note I was testing on small amounts earlier, and it may explain why I was 
> still getting issues with v1.5.0
>
> Related issue #27
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by mcollopy** [comment] 2020-06-11 01:14
@twomice I have taxation enabled, and Financial type is 'Processing Fee', configured for tax as per the [Civi documentation](https://docs.civicrm.org/user/en/latest/contributions/sales-tax-and-vat/).

Just looking at the database line item records, I notice that the 1.5% fee is calculated on the gross
- see the attached example shows the main price is $10, with $1 (10%) tax
- the percentage is calculated as 1.5% of the total i.e. $11, calculated as $0.17 - should it be $0.15?
- tax is therefore 10% of $0.17 which is $0.02

Hope that helps, thanks

![Screen Shot 2020-06-11 at 11 06 17 am](https://user-images.githubusercontent.com/1475720/84334021-a6ea2280-abd4-11ea-90f7-17ea81a3471f.png)

**Comment by twomice** [comment] 2020-08-07 16:23
HI @mcollopy . Maybe we're not understanding the right steps to reproduce the error. We've tried these steps, but don't see the bad behavior:

From notes:

> I tried to reproduce this but could not. Here's what I tried:
> 
> 1. Created a financial type called Taxable Items
> 1. Created a price set called Test PS and assigned Taxable Items as default financial type
> 1. Created price field called Donation Option as radio button with a value of $200, $100 and $10
> 1. Created another price field called Online Processing Fee with a Field Calculate as Percentage of 1.5, Apply percentage box as checked and Taxable Items as financial type
> 1. Created a contribution page called Test Contribution page with Taxable Items as financial type
> 1. Assigned Test Contribution page in CiviContribute Component Settings and enabled tax and invoicing
>
> Previewing the price set doesn't have an error. I expected in the preview that if I checked Online Processing Fee and select the $10 field, then It will not add the 1.5 additional. But I observed that it does add the 1.5 additional.  This looks like correct behavior.

Mick, if you can provide an equivalent set of steps (1. do x; 2. do y; 3. etc.; I expected A but observed B), we'll try those steps here. Thanks!

**Comment by mattwire** [comment] 2022-06-11 13:49
This should be fixed by https://lab.civicrm.org/extensions/mjwshared/-/commit/6bd9c065448627be6c3e833f6476246950464193 which will be in Payment Shared (mjwshared) 1.2.6.

**Comment by twomice** [comment] 2024-07-24 23:46
I'm closing this because it's quite old, and is reported to be fixed by changes in mjwshared extension. 

If this problem is still an issue with the newest versions of mjwshared and percentagepricesetfield, please feel free to re-open this ticket, providing, as far as possible, steps to reproduce the bad behavior.

**Closed by twomice** 2024-07-24 23:46 UTC
Labels: developer needs info
