### ISSUE TITLE
Stripe payment processor not working with added percentage.

### ISSUE THREAD

**Issue by dandrzejewski** [twomice/com.joineryhq.percentagepricesetfield#27] opened 2020-02-25 22:05 UTC
When using this with the Stripe payment processor, it does not work correctly.  I believe this is because the initial authorization is for the total amount WITHOUT the added percentage.  Then it tries to complete the transaction WITH the added percentage, but that's not allowed.

`Credit Card This PaymentIntent's amount could not be updated because it has a status of requires_capture. You may only update the amount of a PaymentIntent with one of the following statuses: requires_payment_method, requires_confirmation, requires_action.`

Not sure if this is an issue with this extension or with the stripe extension.

**Comment by mwestergaard** [comment] 2020-02-25 22:15
I might be seeing a similar behavior. I recently began using the OmniPay extension (nz.co.fuzion.omnipaymultiprocessor) with PayPal Checkout. The added percentage is no longer included in the total processed by PayPal. Civi still records it, but it is left out of PayPal's transaction.

**Comment by twomice** [comment] 2020-02-25 23:21
@mwestergaard I'd like to keep this ticket just for Stripe. Would you mind creating a separate ticket for OmniPay / PayPal Checkout? Also, I don't have easy access to test with with that payment processor. It would be very helpful if you could include in that ticket some screenshots showing the details of where you see the percentage and where you don't. Thanks!

**Comment by twomice** [comment] 2020-02-25 23:30
@dandrzejewski Okay, I see it too. Attached image is a screenshot from my test with Stripe.
![percentage-with-stripe](https://user-images.githubusercontent.com/759449/75296663-6f0cca00-57f3-11ea-844a-9ea7374495e7.png)

My guess is that this extension's use of `hook_civicrm_buildAmount` is incompatible with the way Stripe handles things: the payment is sent directly to Stripe in one http request, and it's submitted to to CiviCRM in another; and it's that civicrm step that invokes `hook_civicrm_buildAmount` to make the final price value on that "extra percentage" line item.

Need to think about this one. Sorry I don't have an easy fix at the moment.

**Comment by twomice** [comment] 2020-02-25 23:38
I've raised a general question about `hook_civicrm_buildAmount` with the Sripe extension developer, just to get some additional info: https://lab.civicrm.org/extensions/stripe/issues/169

**Comment by twomice** [comment] 2020-02-25 23:49
Note from the Stripe developer says `hook_civicrm_buildAmount` is indeed something to be careful with in Stripe, and points to https://github.com/fuzionnz/nz.co.fuzion.extrafee which is reported to use them well together. I'll have to have a look and see what I can come up with.

**Comment by andyburnsco** [comment] 2020-03-07 17:53
FYI, I'm still running Stripe 5.4.1 and percentage price field still works.

**Comment by danielstrum** [comment] 2020-05-23 17:53
I am also having this issue. I am using Stripe. Since implementing this extension a few weeks ago, all (3) transactions that tried to add the percentage have failed. I just tested it and got this same error (see attached).
![Screenshot from 2020-05-23 09-55-40](https://user-images.githubusercontent.com/930536/82737084-38fcba80-9cfc-11ea-8905-d705e6723060.png)

I have now implemented the ExtraFee extension referenced above and it is working. I would rather use this extension but I understand if it might not be worth the work needed to make it compatible with Stripe.

**Comment by twomice** [comment] 2020-05-25 17:50
Thanks for the report @danielstrum . Please tell me: which version of the CiviCRM Stripe extension are you running?

**Comment by danielstrum** [comment] 2020-05-25 23:46
Hi @twomice... It is Civi/Stripe V6.4. Let me know if you need any other info and... thanks

**Comment by twomice** [comment] 2020-05-29 20:33
Fixed! We've now patched this issue in 7f38a55, which is included in v1.5.0-rc1.  If someone here is able to review and confirm that the issue is resolved in that version, I'll cut a release of 1.5.0.  Thanks for reporting, and for testing!

**Comment by twomice** [comment] 2020-05-29 21:53
Correction: v1.5.0-rc2 is better.

**Comment by danielstrum** [comment] 2020-05-31 22:56
Thanks @twomice 
I tested on my dev site and the transaction went through no problem.  I did notice that the version number now listed in the ext list in Civi is 1.5.0-rc1, even though I installed rc2. No biggie but I thought I'd let you know.
Again, thanks!

**Comment by twomice** [comment] 2020-06-01 11:01
Thanks @danielstrum ! We've now tagged v1.5.0, which should show as the latest release at https://civicrm.org/extensions/percentage-price-field within 24 hours.

**Closed** 2020-06-01 11:01 UTC

**Comment by mcollopy** [comment] 2020-06-02 05:39
Hi @twomice, I still get the issue on v1.5.0 on my dev, after running updates, clearing caches etc
"This PaymentIntent's amount could not be updated because it has a status of requires_capture..."
Civi 5.25.0, Wordpress 5.4.1, php 7.2.24-0ubuntu0.18.04.6

Also noticed the GST is being displayed as $0.10
- with the field disabled, the GST displays correctly as $36.36
- when enabled it displays as $0.10 which I assume is coming from the rate of 10%
- it should be 5.45 + 36.36  = 41.81
![Screen Shot 2020-06-02 at 3 19 02 pm](https://user-images.githubusercontent.com/1475720/83483092-36ad1400-a4e5-11ea-991b-64bf4bb4e38a.png)

**Comment by twomice** [comment] 2020-06-02 14:15
Hi @mcollopy Sorry to hear about this trouble. One difference I see is that you have GST enabled on your site, which I and others don't (or have not reported). Right now I'm suspecting GST is relevant here. 

1. Are you able to disable that (either temporarily or on a dev copy of the site) and tell whether that makes a difference?
2. Also, could you provide a screenshot of your price field configuration?

Thanks!

**Comment by mcollopy** [comment] 2020-06-03 06:20
Hi @twomice, still getting the issue after
- disabling GST
- using Financial type Donation only (no GST account)
- new Test price set with Donation Options, and Online Processing Fee 1.5%
Interestingly, the issue was replicated as long as the percentage price was enabled, regardless of whether 'apply to tax amount' was enabled, or if an attempt to pay without selecting the field.
![2c Percentage price field](https://user-images.githubusercontent.com/1475720/83602510-05504900-a5b6-11ea-8e1a-a222ada5089e.png)
![3 Confirmation page](https://user-images.githubusercontent.com/1475720/83602525-097c6680-a5b6-11ea-816f-64b84bacecf9.png)
![2b Price Set Options](https://user-images.githubusercontent.com/1475720/83602527-0aad9380-a5b6-11ea-85b5-ccca1d422b55.png)
![2a Price Set](https://user-images.githubusercontent.com/1475720/83602531-0bdec080-a5b6-11ea-8972-6652fa8e22c1.png)
![1 Error message](https://user-images.githubusercontent.com/1475720/83602536-0ed9b100-a5b6-11ea-9de0-a07946efbb9a.png)

**Comment by twomice** [comment] 2020-06-03 14:28
This is great detail, @mcollopy -- thanks! Our first objective in resolving this is to be able to reproduce the error predictably, so I'll use these details to focus on that. If we can't get this to reproduce, we're kinda stuck and won't be able to formulate a solution, in which case I'll be back asking you for more help with reproduction steps.

**Comment by mcollopy** [comment] 2020-06-05 07:14
Hi @twomice - wondering if this might help - a pricing option appears to be automatically created for $1 with $0.10 tax, which could explain the GST amount.

I discovered this by converting the field back to a regular checkbox, and viewing pricing options.
See attached
![Screen Shot 2020-06-05 at 5 10 31 pm](https://user-images.githubusercontent.com/1475720/83847628-edacc800-a74f-11ea-8e6d-dd56b4d921fc.png)

As a regular checkbox field, test contributions work fine.
However when changed to percentage, I still get the error as previously reported.

Thanks

**Comment by twomice** [comment] 2020-06-05 18:13
Hi @mcollopy Good news: We are able to reproduce the bad behavior when the Percentage Price Field has a taxable Financial Type. 

We are not able to reproduce the bad behavior in the other situation you describe:

> still getting the issue after
> * disabling GST
> * using Financial type Donation only (no GST account)
> * new Test price set with Donation Options, and Online Processing Fee 1.5%
> Interestingly, the issue was replicated as long as the percentage price was enabled, regardless of whether 'apply to tax amount' was enabled, or if an attempt to pay without selecting the field.

so we will not pursue this behavior in this ticket; we'll focus for now on a resolution to supporting taxable financial types for the Percentage Priced Field, and if other issues persist after that we'll address them in separate tickets.

**Comment by twomice** [comment] 2020-06-05 19:15
@mcollopy Would you be able to test the latest master branch? We've pushed a fix in 2b35c00 which aims to support taxable Financial Types for the percentage field. Please let me know if you need help testing; your feedback is quite valuable helping us resolve this issue.

**Comment by mcollopy** [comment] 2020-06-06 00:21
Thanks @twomice - I think we may have a solution, as it passed the test on both accounts.
- correct GST
- successful transaction on Stripe test account (no 'requires_capture' message)
<img width="939" alt="Screen Shot 2020-06-06 at 10 07 01 am" src="https://user-images.githubusercontent.com/1475720/83931263-192ac380-a7df-11ea-8417-34e9bd1047f7.png">

Note that the GST worked on the first field I created, but the 2nd issue only cleared after disabling the first field, and creating a new one.  Not sure if that's a caching thing, or something recorded in the field metadata.

Next step is to get my client to do a live test using Stripe - will let you know.

Much appreciation for your prompt turnaround on this one!

**Comment by mcollopy** [comment] 2020-06-06 07:30
Successfully made a live payment of $50 + 1.5% processing fee.
However the summary line only displayed the processing fee GST, not the total GST, and the contribution mount was overstated by the line item GST.  See attached

<img width="939" alt="Screen Shot 2020-06-06 at 5 17 44 pm" src="https://user-images.githubusercontent.com/1475720/83938704-34ff8b00-a81a-11ea-8010-7db6fa6971e5.png">

Another finding was that it wouldn't work on small amounts e.g $10, $20
- I could replicate the 'requires_capture' issue using these amounts
- $50 was successful test and live
- note I was testing on small amounts earlier, and it may explain why I was still getting issues with v1.5.0

**Comment by twomice** [comment] 2020-06-09 15:19
HI @mcollopy Thanks for confirming that the initial issue is resolved. I'd like to close this ticket. Would you mind starting separate tickets for the other issues you mentioned?

**Comment by mcollopy** [comment] 2020-06-09 21:33
Hi @twomice - thanks for your help, but please note as above the issue is resolved, but not for small amounts < $50

> Another finding was that it wouldn't work on small amounts e.g $10, $20
> 
> I could replicate the 'requires_capture' issue using these amounts
> $50 was successful test and live
> note I was testing on small amounts earlier, and it may explain why I was still getting issues with v1.5.0

I will open another ticket RE GST amounts.  Thanks.

**Comment by mcollopy** [comment] 2020-06-11 00:17
@twomice I have created a [new issue here](https://github.com/twomice/com.joineryhq.percentagepricesetfield/issues/36), thanks.

**Comment by twomice** [comment] 2020-06-11 00:46
Thanks Mick!

Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail
