### ISSUE TITLE
Wrong total amount in 1.2Beta6 / Joomla

### ISSUE THREAD

**Issue by hair-transplant** [twomice/com.joineryhq.percentagepricesetfield#22] opened 2018-02-02 18:36 UTC
We are using CiviCRM 4.7.29 / Joomla with european data (that means , = decimal point)
On data entry page the total amount is wrong (here 3%)

![mwsnap193](https://user-images.githubusercontent.com/35275822/35748865-cb768592-084f-11e8-9bd9-d384d5f3126d.jpg)
In second page (confirmation page) data is correct.

Reason for this is in public_price_set_form.js / around line 93
I was able to correct the problem by dividing with 100
`// **MODI**
      finalTotal = Math.round(total*100)/10000;
    }
    else {
// **MODI**
      finalTotal = baseTotal/100;
    }`
I´m pretty sure that there is a deaper reason behind it connected to handling of decimal points

**Comment by twomice** [comment] 2018-02-02 18:57
Good catch. I think CiviCRM has some utilities for handling decimals which we can use to clean up the amounts before applying math. I'm marking this as a bug. If you have a PR I'm glad to review it. Thanks for the report.

**Comment by hair-transplant** [comment] 2018-02-02 19:20
Hallo!

thx for the quick reply.
1) What do you mean by "If you have a PR " ...... PR = ???
2) second finding I just made: it does not work on our membership page, .... but this is also not on your list of tested options in the README.md. Did you ever try ?
Life site is https://www.fue-europe.com 


Ludger
 

 
Sender: Allen Shaw
Send Time: 2018-02-02 19:57
Receiver: twomice/com.joineryhq.percentagepricesetfield
cc: hair-transplant; Author
Subject: Re: [twomice/com.joineryhq.percentagepricesetfield] Wrong total amount in 1.2Beta6 / Joomla (#22)
 
Good catch. I think CiviCRM has some utilities for handling decimals which we can use to clean up the amounts before applying math. I'm marking this as a bug. If you have a PR I'm glad to review it. Thanks for the report.

**Comment by twomice** [comment] 2018-02-02 19:30
Hi,

1. Sorry, that's geeky github talk. PR means "Pull Request" which is a way of submitting code changes on github.  Perhaps I should have said, "if you have a code fix ..."
2. Seems like it should work on membership pages, since that is handled through Contribution Pages. (e.g., https://www.fue-europe.com/membership-sign-up is a Contribution Page with membership options, right?)  If you can, please create a separate issue for the functionality on membership pages.

Thanks!

**Comment by hair-transplant** [comment] 2018-02-02 19:54
I have a workaround (see above), but I fear that might not be a real solution for all purposes.
I saw that there has been done alot of work in the last versions for CiviCRM handling the ./, - problem, and actually there has been some problems with cividiscount as well. 
Just documented and added a separate issue for the membership page

**Comment by twomice** [comment] 2024-07-27 23:02
Clearly I have neglected this issue for a long time. I believe that in the interim, this issue has been resolved, or perhaps there is more detail I will need in order to reproduce it. 

Here's a screenshot (under the latest extension version 1.5.3, released today) with CiviCRM 5.74.4 in Joomla, showing correct calculation of the percentage:

![jj](https://github.com/user-attachments/assets/846f6b2a-56f7-4c7f-88a5-d770af4dc1a3)

(Some bugs were recently fixed in this latest version, related to percentage calculation, so this may have solved the problem in this issue also. See #57, #60, #62).

With all that in mind, I'll close this issue for now. If you're still interested in this issue and think it needs more attention, please try in this latest version, and then feel free to re-open this issue with details about the problem you're seeing. Thanks @hair-transplant !

**Closed by twomice** 2024-07-27 23:02 UTC
Labels: bug
